apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus-yhac
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-cutg-tenant/quarkus/devfile-sample-code-with-quarkus-yhac@sha256:146c21e008034bbf544295aeb5ec0f96412449b0f33f2e1faed7afa121b631ee
        name: my-java-quarkus
        resources: {}
status: {}
